// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9KrDBWDQnPNX9Chx-cuDoruM8oVDQqsc',
    appId: '1:1005167135828:web:d6b9fca20cb60e1f2131c1',
    messagingSenderId: '1005167135828',
    projectId: 'kitahackkk',
    authDomain: 'kitahackkk.firebaseapp.com',
    storageBucket: 'kitahackkk.firebasestorage.app',
    measurementId: 'G-QXVVG6MTF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGFlb9Ma98DFkOimeR06cQLtN_7LMA7sI',
    appId: '1:1005167135828:android:b9d2a7ed214b32012131c1',
    messagingSenderId: '1005167135828',
    projectId: 'kitahackkk',
    storageBucket: 'kitahackkk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuLz8F3ZudyfG37Ji_BhXwQxPisbbZIqU',
    appId: '1:1005167135828:ios:b1031a458ddde8a92131c1',
    messagingSenderId: '1005167135828',
    projectId: 'kitahackkk',
    storageBucket: 'kitahackkk.firebasestorage.app',
    iosBundleId: 'com.example.kitahack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuLz8F3ZudyfG37Ji_BhXwQxPisbbZIqU',
    appId: '1:1005167135828:ios:b1031a458ddde8a92131c1',
    messagingSenderId: '1005167135828',
    projectId: 'kitahackkk',
    storageBucket: 'kitahackkk.firebasestorage.app',
    iosBundleId: 'com.example.kitahack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9KrDBWDQnPNX9Chx-cuDoruM8oVDQqsc',
    appId: '1:1005167135828:web:2a83b4e77f4a68332131c1',
    messagingSenderId: '1005167135828',
    projectId: 'kitahackkk',
    authDomain: 'kitahackkk.firebaseapp.com',
    storageBucket: 'kitahackkk.firebasestorage.app',
    measurementId: 'G-F254L4MZJ8',
  );
}
